version: '3.8'

services:
  postgres:
    image: postgres:14.6-alpine
    container_name: identity_reconciliation_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: identity_reconciliation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  
  migrations:
    image: flyway/flyway:9.14-alpine
    container_name: identity_reconciliation_db_migrations
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/identity_reconciliation
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: password
    volumes:
      - ./src/database/migrations:/flyway/sql
    command: ["migrate"]
    depends_on:
      - postgres

networks:
  default:
    name: identity_reconciliation_network
